after-startup-command = ['exec-and-forget brew services start sketchybar',
'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=1.0']

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-focus-changed = ['exec-and-forget /Users/jordanb/.config/sketchybar/plugins/update_workspaces.sh']

[gaps]
	inner.horizontal = 8
	inner.vertical = 8
	outer.left = 8
	outer.right = 8
	outer.top = 40
	outer.bottom = 8


# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}

[mode.main.binding]
    # View Modes
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # Focus Commands
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # Move Commands
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Resize Commands
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # Change Active Workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'

    # Move to Workspace Commands
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'

    # Back and Forth
    alt-tab = 'workspace-back-and-forth'